version: "3.9"

services:

  orderservice:
    image: orderservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      DB_CONNECTION_STRING: Host=postgresdb;Port=5432;Username=postgres;Password=1234;Database=postgresdb

  postgresdb:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:latest
    ports:
      - "6060:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - orderservice

volumes:
  postgres_data: