version: '3.9'
services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ordersdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432" 

  orderservice:
    build: .
    restart: always
    depends_on:
      - postgresdb
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgresdb;Port=5432;Database=ordersdb;Username=postgres;Password=1234
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - orderservice
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email your@email.com
      --agree-tos
      --no-eff-email
      -d orderb.hopto.org"

volumes:
  postgres_data: